name: Build PS2 Game
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container: ps2dev/ps2dev:latest
    steps:
      - uses: actions/checkout@v4

      - name: Install gsKit and Dependencies
        run: |
          apk add --no-cache make
          # Pobieramy gotowe paczki bibliotek dla PS2
          ps2-packer-init
          ps2-sdk-setup
          # Instalujemy gsKit z repozytorium portów
          ps2-port-setup gskit

      - name: Compile Game
        run: |
          # Eksportujemy sciezki, zeby Makefile je widzial
          export GS_KIT=$PS2DEV/gsKit
          make

      - name: Upload ELF
        uses: actions/upload-artifact@v4
        with:
          name: PS2-Game-File
          path: MAIN.ELF
