name: Build PS2 Game
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container: ps2dev/ps2dev:latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Tools
        run: |
          apk add make
      - name: Compile Game
        run: |
          make
      - name: Upload ELF
        uses: actions/upload-artifact@v4
        with:
          name: PS2-Game-File
          path: MAIN.ELF
